#!/bin/bash

set -e # If any command fails, stop execution of the hook with that error

juju-log "Entered the MITREid Connect Server charm install hook."

apt-get update
apt-get -y --no-install-recommends install openjdk-7-jdk
apt-get -y install curl

# some common tools
mkdir /opt/tools
curl http://apache.openmirror.de/maven/maven-3/3.2.1/binaries/apache-maven-3.2.1-bin.tar.gz | tar xz -C /opt/tools
for i in /opt/tools/*/bin/*; do ln -s $i /usr/bin ; done

apt-get install -y git

juju-log "Java, Git and Maven successfully installed."

rm -rf OpenID-Connect-Java-Spring-Server
git clone https://github.com/instauth/OpenID-Connect-Java-Spring-Server.git

juju-log "MITREid Connect Server successfully cloned."

/usr/bin/mvn -Dmaven.test.skip=true -f OpenID-Connect-Java-Spring-Server/pom.xml install

juju-log "MITREid Connect Server successfully installed."

exit 0
