#!/bin/bash

set -e # If any command fails, stop execution of the hook with that error

juju-log "Entered the MITREid Connect Server charm install hook."

apt-get install -y software-properties-common
add-apt-repository -y ppa:webupd8team/java
apt-get update
echo debconf shared/accepted-oracle-license-v1-1 select true | debconf-set-selections
echo debconf shared/accepted-oracle-license-v1-1 seen true | debconf-set-selections
apt-get install -y oracle-java7-installer

apt-get install -y git
apt-get install -y maven

juju-log "Java, Git and Maven successfully installed."

rm -rf OpenID-Connect-Java-Spring-Server
git clone https://github.com/instauth/OpenID-Connect-Java-Spring-Server.git

juju-log "MITREid Connect Server successfully cloned."

/usr/bin/mvn -Dmaven.test.skip=true -f OpenID-Connect-Java-Spring-Server/pom.xml install

juju-log "MITREid Connect Server successfully installed."

exit 0
