#!/bin/bash

set -e # If any command fails, stop execution of the hook with that error

source "$(dirname "$0")/config.sh"

juju-log "Entered the MITREid Connect Server charm start hook."

juju-log "Opening port $PORT for MITREid Connect Server"
open-port $PORT

if [ -f .lock ]; then juju-log "Lockfile present. Already started." ; exit 0 ; fi

BASEURL=$(base_url)

juju-log "Configured base URL: $BASEURL"

/usr/bin/mvn -D jetty.port=$PORT -D oic.baseurl="$BASEURL" -f OpenID-Connect-Java-Spring-Server/openid-connect-server-webapp/pom.xml jetty:run > /var/log/jetty.log &
disown

juju-log "MITREid Connect Server starting..."

touch .lock

juju-log "Lockfile created."
