#!/bin/bash

set -e # If any command fails, stop execution of the hook with that error

source "$(dirname "$0")/config.sh"

juju-log "$APP_LONG_NAME stopping..."

killall java

rm -f .lock && juju-log "Removed lockfile - waiting 30 seconds." && sleep 30
