#!/bin/bash

set -e # If any command fails, stop execution of the hook with that error

juju-log "Entered the MITREid Connect Server charm stop hook."

juju-log "MITREid Connect Server stopping..."

rm .lock && juju-log "Removed lockfile - waiting 30 seconds." && sleep 30
